version: '3.7'
networks:
  cryptopunk:
services:
  api:
    container_name: cp-api
    build:
      context: .
    depends_on:
      - mongo
      - redis
    volumes:
      - ./:/usr/app
      - /usr/app/node_modules/
    networks:
      - cryptopunk
    environment:
      - PORT=8080
      - MONGODB_CONNECTION_STRING=mongodb://cp-mongo:27017/cp-tokens
      - REDIS_HOST=cp-redis
      - REDIS_PORT=6379
      - LOGGER_LEVEL=verbose
      - CACHE_DEFAULT_TTL=900000
      - CACHE_VERIFY_CODE_TTL=900000
      - AUTH_TOKEN_SECRET=AUTH_TOKEN_SECRET
      - AUTH_TOKEN_EXPIRATION=24h
      - AUTH_REFRESH_TOKEN_SECRET=AUTH_REFRESH_TOKEN_SECRET
      - AUTH_REFRESH_TOKEN_EXPIRATION=10d
      - SENDGRID_API_KEY=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
      - SENDGRID_SENDER=contact@vera.services
      - BLOCKCHAIN_NODE_RPC=https://eth-mainnet.g.alchemy.com/v2/aY6f-cGc3eWNAEjpOJnPTezZL8WP3UXs
      - BLOCKCHAIN_TOKEN_CONTRACT=0xb47e3cd837dDF8e4c57F05d70Ab865de6e193BBB
      - BLOCKCHAIN_MULTICALL_CONTRACT=0xcA11bde05977b3631167028862bE2a173976CA11
      - BLOCKCHAIN_MULTICALL_LIMIT=500
    ports:
      - '8080:8080'
  mongo:
    container_name: cp-mongo
    image: mongo:latest
    ports:
      - "27018:27017"
    volumes:
      - mongo-db:/data/db
    networks:
      - cryptopunk
  redis:
    container_name: cp-redis
    image: redis:alpine
    command: redis-server
    ports:
      - "6380:6379"
    environment:
      - REDIS_REPLICATION_MODE=master
    networks:
      - cryptopunk
volumes:
  mongo-db:
